-- AlterTable
ALTER TABLE `movielist` ADD COLUMN `description` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `genreIds` VARCHAR(191) NOT NULL DEFAULT '[]',
    ADD COLUMN `overview` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `rating` VARCHAR(191) NOT NULL DEFAULT 'N/A',
    ADD COLUMN `releaseDate` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `votes` VARCHAR(191) NOT NULL DEFAULT '0';
